### ISSUE TITLE
AttributeError - NoneType object has no attribute start

### ISSUE THREAD

**Issue by twentytwokhz** [nielstron/quantulum3#38] opened 2018-08-31 11:09 UTC
**Describe the bug**
When calling parser.parse on certain strings this error is thrown

**To Reproduce**
1. parser.parse('approximately one and one-half miles east')
4. See error: AttributeError("'NoneType' object has no attribute 'start'",)

**Expected behavior**
No error

**Additional information:**
 - Python Version: 3.6.6
 - OS: Windows 10
 - Version 

**Additional context**
https://github.com/nielstron/quantulum3/blob/cba43491fde0ebade385eaeec7fffb6d34a1e954/quantulum3/parser.py#L521

**Comment by nielstron** [comment] 2018-08-31 12:11
Line reference:

https://github.com/nielstron/quantulum3/blob/cba43491fde0ebade385eaeec7fffb6d34a1e954/quantulum3/parser.py#L521

**Comment by nielstron** [comment] 2018-08-31 13:18
Why did you close this issue? Is the error not occurring anymore?

**Comment by nielstron** [comment] 2018-09-01 23:00
Can confirm that this is caused by "one-half". Two errors here. One is linked to #40 and #1. One is that it should be checked whether the word we searched for is actually a word on its own in the text. Before the referenced line, there should be a check whether the match was successful.

**Comment by nielstron** [comment] 2018-09-06 23:00
The first problem is fixed now. The harder part is the second problem for which I have to create a number parser I guess.

**Closed** 2018-10-08 20:51 UTC
